app_name: "desktop"

mqtt:
  server_host: "localhost"
  server_port: 1883
  keep_alive: 5
  retain_last_will: true
# optional user and password
# user = "user"
# password = "password"

homeassistant:
  autodiscover: true
  # prefix in the default mqtt configuration, needs to be changed if it's different in homeassistant
  autodiscover_prefix: "homeassistant"

  # all entities will belong to this device
  device: &device
    name: "desktop"
    identifiers:
      - "desktop-util"

switch_on_value: "ON"
switch_off_value: "OFF"

sway:
  mqtt_name: "desktop_sway"
  name_prefix: "sway_"

  state_topic: &sway_state "desktop/sway/state"
  command_topic: &sway_command "desktop/sway/command"
  availability: &sway_availability
    payload_available: "online"
    payload_not_available: "offline"
    topic: "desktop/sway/availability"

  # workspaces_select:
  #   name: "sway_workspaces"
  #   object_id: "sway_workspaces"
  #   unique_id: "sway_workspaces"
  #   # value_template: "{{ (value_json.workspaces | selectattr('focused', 'equalto', true) | first).name }}"
  #   value_template: "{{ value_json.current_workspace }}"
  #   command_topic: *sway_command
  #   state_topic: *sway_state
  #   availability: *sway_availability
  #   device: *device
  #   json_attributes_topic: ""
  #   json_attributes_template: ""

pulseaudio:
  mqtt_name: "desktop_pulse"
  state_topic: "desktop/pulse/state"
  command_topic: "desktop/pulse/command"

  availability: &pulse_availability
    payload_available: "online"
    payload_not_available: "offline"
    topic: "desktop/pulse/availability"

  # sink_select:
  #   name: "pulse_sinks"
  #   object_id: "pulse_sinks"
  #   unique_id: "pulse_sinks"
  #   command_topic: "pulse/sinks/select"
  #   state_topic: "pulse/sinks/state"
  #   availability: *pulse_availability
  #   device: *device
